language: cpp
sudo: required
dist: trusty

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - git clone https://github.com/ocornut/imgui ../imgui

script: 
  - make -C app
  - app/imgui_test_app -nogui -v2 -nopause
