name: Tests

on:
  push: {}
  pull_request: {}

jobs:
  Linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        branch: [master, docking, tables, features/range_select]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        repository: ocornut/imgui
        ref: ${{ matrix.branch }}

    - name: Build
      run: |
        make -C test_app/

    - name: Test
      run: |
        timeout 300 test_app/imgui_test_app -nogui -nopause -v2 -ve4 tests
